### ISSUE TITLE
Pulling in Instagram videos?

### ISSUE THREAD

**Issue by JooStrappin** [stevenschobert/instafeed.js#225]
Hi Steven,

Can "Insafeed.js" pull in Instagram videos? I've read through all the info over at http://instafeedjs.com/ and didn't see anything in the code blocks that mention anything about pulling in videos, so I'm assuming this isn't possible? If not, is this something that is even realistic to add to instafeed.js?

**Scenario:**
Working on a project where the client wants to showcase images by tag name on a given webpage. Which is deadset simple using instafeed.js. But on that same page, they also want to showcase a couple instagram videos by tagname. 

It looks like I can manually get Instagram embed code for videos, but was hoping for a way that this could be done programmatically through instafeed.js api hooks.

Any words of wisdom or suggestions? I'm not a jscript buff so maybe I'm complete way off base asking about something that may be completely unrealistic.

Thanks Steven,
Josh

**Comment by stevenschobert** [comment]
Hey @JooStrappin!

Don't worry, you didn't miss anything. There isn't anything in the docs about video support (actually this library was created before Instagram even supported videos!).

It gets tricky because embedding videos usually requires 2 things:
1) getting the source URL of the video file
2) creating a video player (html5/flash/etc) to play that file and displaying it on a page.

Instafeed.js only takes care of the first one for you. Since Instagram's API does provide the URLs of video files (and a flag to know if that image is a video), you can get that information out of Instafeed.js.

However, when it comes to actually displaying the video on your page, that responsibility lies outside what Instafeed.js does. You'd need a video player library, like [videojs](http://www.videojs.com) to handle that.

Hope that helps!

**Comment by JooStrappin** [comment]
Hi @stevenschobert ,

Thanks for your detailed response. Completely makes sense now. Thanks for shedding some light on the subject. Helpful, and much appreciated.
