### ISSUE TITLE
How to get Instafeed to render all on webpage tabs?

### ISSUE THREAD

**Issue by vethcl** [stevenschobert/instafeed.js#324]
Is anyone familiar with how to get Instafeed to render on all tabs of a webpage?

**Comment by stevenschobert** [comment]
Hey @vethcl! Thanks for posting an issue, could you provide a little more clarity around what you mean by "tabs"? Its a little hard to understand what problem you're facing :)

**Comment by vethcl** [comment]
Such as the "shop" page on my webpage, or "about us"? Located on the bar on the top of my page.

**Comment by vethcl** [comment]
I can include a picture if you would like.

**Comment by stevenschobert** [comment]
It sounds like thats going to be specific to how you have your website set up. You'd have to share the details of where you are running your website, how your pages are structured, etc. You'll probably get better help by posting that type of question to stackoverflow.com.

If you have any specific questions about this library or it's APIs though, feel free to post another issue! You can also post the link to your stackoverflow.com question here if you would like people to find it later.

**Comment by vethcl** [comment]
Wonderful, thank you for your help!

**Comment by vethcl** [comment]
I wasn't able to get any responses from stackoverflow.com do you think you can be of any more assistance on this matter?

**Comment by gbrandallen** [comment]
Your asking him for help on your website that is unrelated to his plug-in. Please don't take this the wrong way, and I don't mean anything insulting by this, but that isn't what this forum is for. Your question is an is more geared towards how to set up a website using repeated sections of code across many pages. I will tell you this, if you are using a PHP environment to build your site, you might research using an "include" so that the instafeed.js appears on all of your pages. The snippet of code needed is simple to use and allows you to embed sections your site into multiple pages from one source. Good luck. Cheers.

**Comment by vethcl** [comment]
No offense taken. I understand what you're saying. I'm just not familiar with code at all, it may seem that I'm being ignorant towards the fact that it's unrelated to his plug-in, but I actually just had no idea that it wasn't related. The first time I used/typed any code was figuring out how to get instafeed to appear on my webpage. Thank you for your feedback, I'll research the "include" to see if I can figure out how to do it. PHP is also something I'm not familiar with, but I'll look into that as well. Cheers.

**Comment by gbrandallen** [comment]
No worries. I've been there. Two amazing resources that I've found super helpful in my coding journey are https://teamtreehouse.com/ and https://www.codecademy.com. They are super great at guiding you through the steps of learning the basics and building from there. I wish you well on your learning. Its super fun.
