### ISSUE TITLE
SPAM following after using instafeed.js

### ISSUE THREAD

**Issue by dubbsdubblin** [stevenschobert/instafeed.js#337]
Hi, my Instagram account has 1500+ fake people I am supposedly following since using Instafeed.js - you have a massive security opening somewhere that someone has exploited! Please sort this out ASAP!

**Comment by stevenschobert** [comment]
Sorry you've run into issues! Can you provide some details about how you were using Instafeed.js?

**Comment by jonwallacedesign** [comment]
I just used instafeed.js to work on a website I built, and then over the last few weeks noticed more and more spam / fake people being added to my following list. I have changed passwords since and cleared out the 1500 fake people and hope they will not return. It seemed to co-incide with my usage of instafeed.js on this website.

**Comment by benjamin-hull** [comment]
It's possible this could have been caused by running instafeed.js with an access_token with `follower_list` scope or similar write-permissions... basically, just a nasty side-effect of 'publishing' the access token in the source code. Tokens with these scopes are no longer being issued, so this hole (if that's what it was) has long since closed.
