### ISSUE TITLE
Link for AccessToken Removed - still may be required

### ISSUE THREAD

**Issue by nickfmc** [stevenschobert/instafeed.js#338]
this link was removed from your site with version 1.4.0 however to use certain functions it seams to still be required such as 
<code>
filter: function(image) {
            return image.user_has_liked;
        }
</code>
https://instagram.com/oauth/authorize/?client_id=467ede5a6b9b48ae8e03f4e2582aeeb3&redirect_uri=http://instafeedjs.com&response_type=token

**Comment by stevenschobert** [comment]
Hey @nickfmc, thanks for taking the time to write in!

You are correct, I did remove that link from the project website. My main reason for doing so is to try and discourage the use of `accessToken`, now that its no longer required. Using a client ID is __much safer__ than access tokens, since they don't contain any special security privileges for users.

The downside is that API responses do not "know" who the current user is when you are using client IDs. So when you are trying to access `image.user_has_liked`, it longer know who "user" is. On the one hand that is more secure, but on the other means you can't filter by that property.

I've left support for using `accessToken` in the library, but I'm treating it more like a "power user" feature. So you can continue to use a token if you'd like to have extra functionality, but you'll have to "get" that token on your own, I won't be issuing them anymore.

At some point in the future I plan on removing the little app that was granting tokens for people, and encourage everyone to use client IDs instead for safety.

Hope that makes sense!
