### ISSUE TITLE
Load More button not load all image

### ISSUE THREAD

**Issue by studiocasaliggi** [stevenschobert/instafeed.js#363]
Hello everyone!
I installed this plugin on my site but the load more function does not work well because it loads only part of all the photos that are on the profile.
Why?
The link is: http://zignone.sitobeta.net/feelzignone.html

**Comment by ongerit** [comment]
The link sent is currently unavailable:
http://zignone.sitobeta.net/feelzignone.html

**Comment by studiocasaliggi** [comment]
http://www.zignone.it/feelzignone.html

**Comment by ongerit** [comment]
What is your Instagram username?

**Comment by dkjoseph** [comment]
Can you please unsubscribe jgarrido@thisisdk.com<mailto:jgarrido@thisisdk.com> ?

On Feb 5, 2016, at 12:58 PM, Thomas Ongeri <notifications@github.com<mailto:notifications@github.com>> wrote:


What is your Instagram username?

**Comment by ongerit** [comment]
Is it lanificiozignone?

**Comment by dkjoseph** [comment]
I’m not sure, he is no longer using this email address, they are being forwarded to me..

On Feb 5, 2016, at 1:00 PM, Thomas Ongeri <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it lanificiozignone?

**Comment by ongerit** [comment]
The pagination object is empty from Instagram's json. This is why you aren't able to pull additional images in the feed. The issue lies in instagram's json from my finding. 

https://api.instagram.com/v1/users/2111834677/media/recent?access_token=2111834677.babd949.43f1e9ac93b64bc8aa3b00188f66997d&count=12&max_id=1174562290734275384_2111834677&callback=instafeedCache3beb9dc90d432765.parse

**Comment by studiocasaliggi** [comment]
Ok thanks @ongerit !
How can I fix it?

**Comment by studiocasaliggi** [comment]
Anyone have a solution?
