### ISSUE TITLE
Instagram Sandbox Client limited to 20 media calls

### ISSUE THREAD

**Issue by Charbrec** [stevenschobert/instafeed.js#442]
I have been using Instafeed.js for about a year now without issue, and started implementing the JS on another webpage. In order for us to call the non-square media from Instagram, we had to create another Client in our developer account. In doing so, we enabled non-square media, but we where only able to load 20 images at a time, no matter what our limit was set to. A little research lead us to the info that we are now limited to 20 media calls within Sandbox mode.

When attempting to submit the app for review, choosing the option of

> I want to display my Instagram posts on my website

prompts this response: 

> You do not need to submit for review for this use case. If you are a developer and you want to display Instagram content on your website, then you do not need to submit your app for review. By using a client in sandbox mode, you can still access the last 20 media of any sandbox user that grants you permission.

So it would appear that my Instagram Client is now trapped at only 20 media calls at a time, and we can't seem to find a solution.

Is this an issue that anybody else has experience when working with Instafeed.js since the API changes? Perhaps any known workarounds?

**Comment by gnyangolo** [comment]
currently there is no way around this seems only 20 images can be drawn at a time

**Comment by coolwebs** [comment]
Yeah, that's really put a thorn in my side. It's not the limit on the amount of images being requested that concerns me - rather it is the rate limit set for 500 requests per hour. I'm embedding this Instagram widget as a tile on the front of a homepage that gets a significant amount of traffic. Is there a good chance that the limit goes over from 1000 people looking at the page at once?

Otherwise, I really can't see how we can practically use Instagram (unless it's for the 3 prescribed purposes that only Instagram allows you to submit for review).

boooooo to Instagram I say....

**Comment by willianschenkel** [comment]
Some update about this?

**Comment by richjdsmith** [comment]
@wschenkel 

Just did a bunch of reading over the past few days. Still stuck at 20.
