### ISSUE TITLE
Instagram API Changes

### ISSUE THREAD

**Issue by marshall993** [stevenschobert/instafeed.js#458]
Used this Git a while back with no issues, however, have you accommodated Instagrams latest API changes to make sure this is still working?

**Comment by ashkon** [comment]
My various sites' went down as well. This no longer works bc of the api changes. /users/self/feed isn't an endpoint now. Perhaps public_content or some such thing? 
And ten of you only get up to 20 imgs at once at most in sandbox mode.

**Comment by brodjustice** [comment]
It works for me in sandbox mode. But you must now add extra credentials, something like:

    var feed = new Instafeed({
      get: 'tagged',
      tagName: 'mytagname',
      clientId: 'xxxxxxxxxxxxxxxxxxxxxx',
      accessToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    });
    feed.run();

This is for the case where you are just loading content that is in any case public. I've not yet tried the case where the content is private. In this case, the client-side method is probably not a good idea.

Getting the credentials is a slightly annoying process, but followinging this slightly out of date guide should help:

https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed

Notes to the guide above:
1. You don't need to set up a LAMP as it suggests it not really required and because...
2. Instagram will not longer accept the localhost:3000 as your redirect URI anymore anyway.
3: Just use your website as the redirect URI and than as the last step it will redirect to your website and you will see something like:
http://mywebsite.com/#access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
You can now just copy your access_token out of the URI.

**Comment by NewDimension** [comment]
As far as  I know in sandbox mode you're limited to the _latest_ 20 user posts (not 20 per request, only 20 latest). Did any one figure out how to deal with that? I want to show all posts of an account I own.

**Comment by ashkon** [comment]
@NewDimension I believe you can get "unlimited" access if you've applied and been approved for an app by the Insta team.  That means that you have to have a privacy page, stream (video of what you'll be doing) and I _think_ an https redirect...

**Comment by newdesignideas** [comment]
Just want to confirm that you now *have to* have the access token of the user´s images you want to show. 

I have no idea whether one can still show images from multiple accounts. Seems like, no, on first glance.

**Comment by derdritte** [comment]
I have read a lot about it today, I wonder why I have not heard about this before, but the instagram API no longer allows any kind of "one-off" projects.

These are the guidelines for what will be approved:
https://www.instagram.com/developer/authorization/
