### ISSUE TITLE
Double Post

### ISSUE THREAD

**Issue by Sciortino1491** [stevenschobert/instafeed.js#463]
Hey,

I'm having a very weird issue, my instagram feed is showing up twice. I have it set to show 5 across and it just duplicates them.

ex. https://shop.kidcentral.ca:8202/#/home (scroll to bottom)

if I copy the code exactly to another page on my site it works with no issues (displays 5 across)

Has anybody experienced this issue?

Code:
```
<script type="text/javascript">
  var userFeed = new Instafeed({
    get: 'user',
    userId: 'myid',
    clientId: 'myclientid',
    accessToken: 'myaccesstoken',
    resolution: 'standard_resolution',
    template: '<a href="{{link}}" target="_blank" id="{{id}}"><img src="{{image}}" /></a>',
    sortBy: 'most-recent',
    limit: 5,
    links: false
  });
  userFeed.run();
</script>
```

CSS:

		#instafeed {
		  width: 100%;
		}

		#instafeed a {
		  display: block;
		  padding: 5px;
		  float: left;
		  position: relative;
		  width: 20%;
		}
		
		#instafeed a:hover{
		cursor: pointer;
		-webkit-filter: brightness(90%); /* Chrome, Safari, Opera */
		filter: brightness(90%);
		-o-transition:.3s;
		-ms-transition:.3s;
		-moz-transition:.3s;
		-webkit-transition:.3s;
		transition: 0.3s;			
		}

		
		#instafeed a img {
		  display: block;
		  width: 100%;
		  height: 100%;
		}

**Comment by stevenschobert** [comment]
Hey @Sciortino1491! It looks like your angular setup is actually doing all of the evaluation, and is calling into Instafeed twice, which results in your feed being loaded twice.

Since your issue is related to angular and not Instafeed.js, I'll close this issue. If you need help hunting down your specific issue with angular, try posting your question to Stack Overflow.

Here are the couple of screenshots I grabbed, with a breakpoint set on the `Instafeed.prototype.run` function. On the left-hand side, you'll see the stack trace that leads to the function being called, which looks related to angular to me.

![screen shot 2016-11-18 at 11 07 22 am](https://cloud.githubusercontent.com/assets/896486/20439146/e9206a4e-ad7f-11e6-8a9f-4fa36f6419ab.png)
