### ISSUE TITLE
Using templating {{link}} adds source domain + instagram

### ISSUE THREAD

**Issue by kbrookes** [stevenschobert/instafeed.js#469]
Hi there,

When I use instafeed without templating, everything works perfectly.

When I use templating, it prepends the output of {{link}} with a /

So if I'm working on domain.com, all outbound links fail as they appear as:

http://domain.com/https://www.instagram.com/p/hzLOy8Rcf4/

**Comment by stevenschobert** [comment]
Hey @kbrookes.

That is most likely caused by another script besides Instafeed.js running on the page. You can verify that by copying your settings into an isolated environment, for example just creating a plain html file and pasting in your settings. Or by pasting your settings into something like [JSFiddle](http://jsfiddle.com).

If you're still hitting this problem in a completely isolated setup, please re-open this issue and let me know! Otherwise you may want to try posting the details of your setup on [StackOverflow](http://stackoverflow.com).

**Comment by christopherbisman** [comment]
i have the same problem, 

you could solve it?
