### ISSUE TITLE
Getting by tagname not working

### ISSUE THREAD

**Issue by chengkiang** [stevenschobert/instafeed.js#482]
I can't even get the sample code to work. 

```
<script src="instafeed.js"></script>
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'nofilter',
        clientId: 'my client id',
        template: '<a href="{{link}}"><img src="{{image}}" /></a>'
    });
    feed.run();
</script>
```

Console reports "Uncaught Error: Error from Instagram: This request requires scope=public_content, but this access token is not authorized with this scope. The user must re-authorize your application with scope=public_content to be granted this permissions."

**Comment by ry167** [comment]
You need to add the scope `public_content` to your authorization URL. You can read more about that here: https://www.instagram.com/developer/authorization/

**Comment by liveorgandonor** [comment]
@chengkiang  Because of changes Instagram made, I don't believe the sample code works anymore with just a clientID. I think you need an access token to do pretty much anything with Instafeed. I found @benweltman's comment on [this issue](https://github.com/stevenschobert/instafeed.js/issues/408#issuecomment-256345776) to be a useful summary for how to get around this.
