### ISSUE TITLE
instagram maximum number of requests per hour

### ISSUE THREAD

**Issue by beterthanlife** [stevenschobert/instafeed.js#519]
Hi, we really like instafeed and have a suggestion for a new feature: result caching.

We are occasionally exceeding the instagram request limit and getting this error back:

`{"error_type": "OAuthRateLimitException", "code": 429, "error_message": "You have exceeded the maximum number of requests per hour. You have performed a total of XXXX requests in the last hour. Our general maximum limit is set at 500 requests per hour."}`

We are going to develop our own caching strategy to avoid this in future, but it would be great if there was an option within instafeed itself to enable this somehow.

**Comment by rediris** [comment]
If you're in sandbox mode, it's likely this will keep happening. I suggest using the rate `limit` in the JS, and hopefully this article will prove indispensable: https://css-tricks.com/everything-need-know-instagram-api-integration/

**Comment by HandHugs** [comment]
we are having this issue on our site. We want the instagram feed to appear on all pages, but after about two weeks it gives us the 429 error and the feed stops displaying.

**Comment by benjamin-hull** [comment]
Couple of question, @HandHugs: Does the feed re-activate by itself after a while? And are you getting the same error message as the original post? `You have exceeded the maximum number of requests per hour. You have performed a total of XXXX requests in the last hour. Our general maximum limit is set at 500 requests per hour.`

Assuming it is the same rate-limit error...

Because instafeed.js is a client-side only library, it means that every visitor your site has is making an independent call to the API with the same access token. Caching in the browser could help a bit, in that repeated page loads by the same person would not create multiple requests, but it won't help reduce the number of requests across all your users. If your embedded feed has more than 500 visitors in an hour, you're going to get rate limited no matter what you do.

One thing you could look at (depending on your design, this might or might not be useful), is 'lazy-loading' your feed. For example, you could wait until the user has scrolled down to the feed's container before initializing it, or waiting 5 seconds before initializing so you don't make the request for people who aren't going to see it. That's all dancing around the edges of the real limitation, though.
