### ISSUE TITLE
Unable to generate feed because invalid access token

### ISSUE THREAD

**Issue by ariparikh** [stevenschobert/instafeed.js#575]
Your documentation says I don't need the access token, only client ID...yet I am still seeing the error 

'instafeed.min.js:2 Uncaught Error: Error from Instagram: The access_token provided is invalid.'

Can someone advise? I am trying to pull in ALL public images with a certain hashtag for a course final...

**Comment by mattbag** [comment]
You need it, also as of 4th of April api changed and you have more restrictions, so you might want to check that

**Comment by aaronearl** [comment]
Question is instafeed js working or not?

**Comment by aaronearl** [comment]
Thank you

**Comment by mattiaband** [comment]
@benjamin-hull do you know if it is still possible to "Show my latest n posts" from multiple account?

I have a website that uses instafeed that shows the latest n post from accounts: x,y,z etc

is it still possible with the new Instagram API changes?

thanks

**Comment by benjamin-hull** [comment]
@mattiaband - yes, but you'll need to invite each user to your sandbox, to a maximum of 10 users, per the instructions here: https://www.instagram.com/developer/sandbox#sandbox-users - each user will only provide their latest 20 posts, too - so as long as your _n_ is less than 20, you're good.

**Comment by mattiaband** [comment]
Thanks @benjamin-hull for your answer.
I tried to invite and accept the users to my sandbox (I can see the status "accepted" in my Sandbox list Users) but unfortunately I am still receiving that error. (This endpoint has been retired)
The script works if I add just my userId, but it can't load the other sandbox-users feed.

are you 100% sure that it is possible what you suggested?

I was reading again the API and the endpoints and it seems to me that I can get just the data only of the owner of the access_token or media in a specific location.

https://www.instagram.com/developer/endpoints/users/
https://www.instagram.com/developer/endpoints/media/

i just would like to know if I am doing something wrong or it is no more possible show the feed of other sandbox-users.

Thank you for your help in this matter.

**Comment by benjamin-hull** [comment]
Hi @mattiaband - sorry, I gave you bad info there. I misunderstood some of the recent changes, and Instagram's own documentation hasn't been updated and still has examples which no longer work. Here's my current understanding (matches your own, I think):

Sandbox mode doesn't give you any additional access or endpoints. It really just acts as a scope which defines which user's access tokens are valid inside your app. So, if you and I are both users in the same sandbox, we can supply the sandbox `client_id` and our own individual `access_token`, and then use an endpoint like `/users/self/media/recent/` to get our own media, but we can't get `/users/[your_user_id]/media/recent` because that endpoint requires `public_content` permission, which is no longer being granted, and is never granted in sandbox mode anyway.

The only way I can see around this is to make multiple requests with multiple access tokens (one per user), and then combine the responses yourself afterwards. I know that's very much not ideal, sorry!

**Comment by mattiaband** [comment]
what you suggested "The only way I can see around this is to make multiple requests with multiple access tokens (one per user)" works, thanks!!! ;)

just curiosity, I saw that some apps are able to get the other users's feed without ask for permission (access token etc...)
for example: 
https://elfsight.com/instagram-feed-instashow/

do you know how it is possible?
i guess that they submitted the app to instagram and than instagram accepted it, with this approval finally you can get the users's photo also without their specific permission.
what do you think? is this a possible explanation? 
do you have any ideas? 

thanks

**Comment by benjamin-hull** [comment]
Elfsight and other systems like it work by having a server-side component between your page and instagram: You add elfsight's code, and their server (most likely) screen-scrapes the public photos from instagram for you, and sends them to your page.

The reason I think they'd be screen-scraping is that Instagram wouldn't have ever granted them an API key to provide that service (unless they did _way_ back in the early days, perhaps). IG explicitly used the example of 'embedding content in other platforms' as a use case that was not allowed.

**Comment by benjamin-hull** [comment]
I'm going to close this one for now, as the main issue seems solved. Thanks all!

**Comment by niawdeleon** [comment]
The ff. article helped me get an access token: https://medium.com/@bkwebster/how-to-get-instagram-api-access-token-and-fix-your-broken-feed-c8ad470e3f02
