### ISSUE TITLE
Live feed/auto refresh

### ISSUE THREAD

**Issue by kristofferli** [stevenschobert/instafeed.js#577]
Hi Steven,

First off I want to thank you for the plugin, its really helpful and generous of you to share it—thanks!

Now, i'm writing because I'm trying to use the instafeedjs for a specific project, in which I am trying to have a site display all the images uploaded from two different Instagram accounts, in the same feed which updates automatically, so that as soon as one of these accounts posts a picture it is added to the site—without the site-user having to refresh the site manually. Kind of like a chat system in which two people can post messages to each other without having to reload the website.

I am primarily facing two issues:

ISSUE 1.
How to output the images from two different accounts into the same stream, organised chronologically, but in the same <div>. For instance, first User A posts two images, then User B posts three images, then User A posts one image, but they are shown in the same continuous stream (but in reverse order having the newest image on top) like so:

A (latest image posted)
B
B
B
A
A (first image posted ever)

and secondly,

ISSUE 2.
How do i make sure, that these images are outputted automatically on the site, without the need to update the site manually? Again, think of the chat system which adds the newest message "live" as soon as the user submits it?

I really hope that you've got the time to help me out here, it would be a tremendous help!

Also,I should add, that I am not a very adept coder and already feel about out of my league even using the plugin to begin with—I apologise and hope you can bear with me!

Thanks in advance!

**Comment by benjamin-hull** [comment]
Hi @kristofferli ... I'm afraid what you are trying to do will not work very well because of Instagram's API restrictions. The API that Instafeed.js uses is being phased out, and will be removed completely in 2020. For now, the API you can use will only work in [Sandbox mode](https://www.instagram.com/developer/sandbox/), which limits the users you can access (maximum of 10 pre-selected users), the number of past photos accessible (max 20 most recent), and the rate you can request (max 200 times per hour).

Here's some more reading: 

- Instafeed.js issue/discussion on this https://github.com/stevenschobert/instafeed.js/issues/345
- https://www.instagram.com/developer/sandbox/
- https://techcrunch.com/2018/04/02/instagram-api-limit/

In general, if you are thinking of doing this for a business concern, I would be very careful about investing time and effort into it based on the use of this API. Instafeed.js might be able to be re-worked to use the OpenGraph API that will replace the instagram API, but a lot of the 'exploring' type of functionality will likely not be available as Facebook tightens up privacy restrictions on the data.

If it were me, and I really needed this to work, I would probably look at a screen-scraping. server-side approach - messy, but less likely to break completely long-term. It is a fair bit more involved, development-wise, though.

Last thing, you might be better off asking "How can I?" type questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/instafeedjs), rather than raising them as issues against the repo here - they'll get seen by many more eyes that way!

**Comment by joeygallegos** [comment]
Hi @kristofferli 

Just a suggestion, but I am using a python script that pulls data from Instagram (once a day) and removes the extra data that we do not care about. We then save this data to ``instagram-feed.json`` which we serve up in a PHP REST API that will pull the data from ``instagram-feed.json`` and include it in the other data we serve out to Angular.

When you login and are authenticated with Instagram, you can use [https://www.instagram.com/proxiedpixel/?__a=1](https://www.instagram.com/proxiedpixel/?__a=1) to access the front-end data of a user (or yourself). This is how we are hydrating our user interface. You could make this more complex by caching the images locally and deleting them if the data feed does not contain that media ID in the ``instagram-feed.json``.

Please let me know if you have any questions.
