### ISSUE TITLE
Image resolution set to thumbnail so thumbnail images is showing in lightbox also

### ISSUE THREAD

**Issue by jainnidhi** [stevenschobert/instafeed.js#578]
Hi

I am using this JS and I set the image resolution to thumbnail. 
I used <a href="{{image}}"><a/> for open image in lightbox.
So, thumbnail images are showing in lightbox.
I've used magnific popup for integrating lightbox.
Can you please help me out?

Thanks in advance!

**Comment by benjamin-hull** [comment]
Hi @jainnidhi,

There a couple of ways to handle this: 

1. Just specify the `standard` resolution and use it for both the thumbnail and the lightbox view. Standard resolution images are not huge (640x640px usually), so the extra overhead is generally acceptable. It has the advantage of making the lightbox open faster too, since the image is already cached.
2. Use a [custom template](https://github.com/stevenschobert/instafeed.js#templating) and add the URL to the standard_resolution image yourself, by accessing the `model` template tag, like this: `{{model.images.standard_resolution.url}}`. That does require an extra image request, and also relies on the structure of the `model` data staying the same. 

All in all, I would go with option 1 for simplicity. Good luck!

**Comment by jainnidhi** [comment]
Hi @benjamin-hull, 

Thank you for replying!

I've created a option for user to select the resolution. So, I can't specify the resolution by default.

Is there any other solution?

**Comment by benjamin-hull** [comment]
It's hard to say without knowing exactly what you're working on, but both of the approaches should be applicable, though you would need to incorporate the users' preference into the javascript for approach 2.

In this case, I would definitely use the standard resolution URL everywhere. Then the user's preference can just be used to set a class for CSS/styling, not to actually request the image sizes - much simpler.

Using the standard resolution URL is also good for high-dpi devices (phones, retina screens, etc) - thumbnails display better since they have extra pixels to pack into the smaller dimensions.

**Comment by jainnidhi** [comment]
Thanks for your support but it will not resolve my problem.

I've created a Instagram Feed module for beaver builder plugin and I am asking to user for set the image resolution in that.

**Comment by benjamin-hull** [comment]
Hi @jainnidhi - sounds like this might be outside the scope of the help we can provide here. You might have better luck asking on [Stack Overflow](https://stackoverflow.com/questions/tagged/instafeedjs) with some code examples and a minimal working demo.
