### ISSUE TITLE
Get pots of specified hashtag.

### ISSUE THREAD

**Issue by Alissonfm** [stevenschobert/instafeed.js#579]
Hi, I'm developing an Website and i need display the posts with an hashtag, but i need display the posts of everyone that uses this hashtag, my instafeed only display the post of the user that i have generated the token access, how can I do this??

**Comment by benjamin-hull** [comment]
HI @Alissonfm.

Global hashtag access is no longer available because of Instagram's API restrictions. The API that Instafeed.js uses is being phased out, and will be removed completely in 2020. For now, the API you can use will only work in Sandbox mode, which limits the users you can access (maximum of 10 pre-selected users), the number of past photos accessible (max 20 most recent), and the rate you can request (max 200 times per hour).

See issue #345 for more info/discussion on this.

**Comment by Alissonfm** [comment]
Oh Boy... Really? Do you know other plugin or way to do this?

**Comment by benjamin-hull** [comment]
There's no longer a way to do it with any script or plugin, really: the data just isn't available (well, not unless you're considering a very complicated screen-scraping approach, and that's a whole different discussion). 

Basically, Instagram don't want you doing this sort of thing anymore, so even if you do find a way that works now, it won't keep working in future, and so you can't rely on that functionality.

**Comment by benjamin-hull** [comment]
Closing as complete.
