### ISSUE TITLE
Stackoverflow: SimplyScroll won't move with InstafeedJS

### ISSUE THREAD

**Issue by chetabahana** [stevenschobert/instafeed.js#581]
I have exactly the [_same case_](http://jsfiddle.net/chetabahana/skmhbkbe/) as a question titled: [_SimplyScroll won't move with InstafeedJS_](https://stackoverflow.com/questions/46707274/simplyscroll-wont-move-with-instafeedjs) in Stackoverflow. It was asked 6 months ago with no body answer till to date. Would you please advise.. Thanks.

**Comment by benjamin-hull** [comment]
Hi @chetabahana - could you provide a link to a working codepen or jsfiddle which shows just the content and demonstrates the problem?

One common cause of issues like this is in the order things are initialised. Something like a scroller needs to be initialised after Instafeed.js has inserted the images into the page. You can try using the `success` callback to initialise the scroller?

One other thing - jquery.simplyscroll is no longer supported and hasn't been updated since 2012 - you'd be better off choosing a modern and supported carousel library.

**Comment by chetabahana** [comment]
Hi @benjamin-hull, 
I have try to put a code using the `success` with no success. 
Here is the link to my current fiddle: http://jsfiddle.net/chetabahana/skmhbkbe/

**Comment by benjamin-hull** [comment]
Hey @chetabahana. I can see that your instafeed.js code is loading images into your page as it should. The remaining issue of it not scrolling is really an issue with the scrolling library, not with instafeed.js. I would definitely suggest going with a modern carousel library - if you're already using jQuery, perhaps try something like https://github.com/kenwheeler/slick.

**Comment by chetabahana** [comment]
Hi @benjamin-hull,
Thanks a lot or your suggestion. Having struggling a whole day finally I found a way to make the scrolling works with [_slick_](https://github.com/kenwheeler/slick). I noted that the callback function need to be put on `after` (not in the `success`).

Here is the link to jsfiddle https://jsfiddle.net/chetabahana/8tt7cvqw/ and 
Here is the link where it lives https://chetabahana.github.io/#templatemo-footer

**Comment by benjamin-hull** [comment]
Great - glad you got it working!
