### ISSUE TITLE
Templating {{image}} not working

### ISSUE THREAD

**Issue by pedrsntana** [stevenschobert/instafeed.js#589]
I was messing around with the template and I noticed the {{image}} isn't getting the link.

I copied the templating code in the documentation and it still doesn't work.
```
    var feed = new Instafeed({
        get: 'user',
        userId: 'xxx',
        accessToken: 'xxx',
        template: '<a class="animation" href="{{link}}"><img src="{{image}}" /></a>'
    })
```

Here's what I get in the HTML:
![instafeed-js_issue](https://user-images.githubusercontent.com/32724605/41284748-19c51496-6e32-11e8-8df0-b25019629a7d.png)

I'm using Jekyll and Gulp, although I don't think that should interfere since all scripts are in the same file.

**Comment by benjamin-hull** [comment]
Hey @pedrsntana, this is definitely working in a few other installations I've checked, so it looks like something up with your implementation. I can't be sure, but that HTML display looks like what the browser displays if there's something invalid in the HTML (though it doesn't look like that should be tha case based on your code).

Just to rule a couple of things out:

- Which version of instafeed.js are you using? Update to the latest if possible (Currently [1.4.1](https://github.com/stevenschobert/instafeed.js/releases/tag/v1.4.1).
- Do you get images if you don't provide the `template` option and have instafeed.js put images into the `#instafeed` element in the page (you may need to add that in order to test)? This will just make sure you're getting valid images back from instagram.

If both of those work, try adding the following to your Instafeed options:

```javascript
success: function(response){
  console.log("Instafeed.js response", response);
}
```

This will output the instagram response to the console - copy it back into the issue here if you need more help and we'll see what else we can do.

Thanks!

**Comment by curtis** [comment]
@pedrsntana if you're using Jekyll, be sure to escape the curly braces in your template. 

```
var feed = new Instafeed({
  get: 'user',
  userId: 'xxx',
  accessToken: 'xxx',
  template: '<a class="animation" href="\{\{link\}\}"><img src="\{\{image\}\}" /></a>'
})
```

Jekyll also uses that notation and will try to process it first. By the time the template is passed to Instafeed, it's already been munged.

Let me know if that helps!

**Comment by philiphoyos** [comment]
If you are using this with Flask you should be escaping { with \ like @curtis points out
template: '<a class="animation" href="\{\{link\}\}"><img src="\{\{image\}\}" /></a>'
