### ISSUE TITLE
next() Breaks CSS Grid

### ISSUE THREAD

**Issue by WolfieeifloW** [stevenschobert/instafeed.js#592]
Hello. I'm using CSS Grid to display all the photos pulled in by instafeed.js. It works for the first set of photos perfectly, but when I add a "Load More..." button using the `next()` function it entirely breaks the grid layout.

The image shows the first red box which are the initial images that load fine then a second red box which are the images that load when using `next()`.

![image](https://user-images.githubusercontent.com/40577712/42112180-066605dc-7bb5-11e8-8371-4aa3ffe2291f.png)

```
<style>
    .grid-gallery {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(200px, auto));
        grid-auto-rows: 200px;
        grid-gap: 1em;
    }

    @supports (display: grid) {
        .grid-gallery-item {
            margin: 0;
            max-width: none;
        }
    }

    .grid-gallery-item:first-child {
        grid-row: span 2;
        grid-column: span 2;
    }

    .grid-gallery-item:nth-child(3n+1):nth-child(even) {
        grid-row: span 2;
    }

    .grid-gallery-item:nth-child(3n+1):nth-child(odd) {
        grid-column: span 2;
    }

    .grid-gallery-item > img {
        width: 100%;
        /*max-*/height: 100%;
        object-fit: cover;
    }
</style>

<div class="container">
    <div id="instafeed" class="grid-gallery"></div>

    <div class="row">
        <div class="col-xs-offset-2 col-xs-8 col-md-offset-5 col-md-2">
            <button type="button" class="btn btn-md btn-primary btn-block" name="load-more" id="load-more">Load More...</button>
        </div>
    </div>

    <script type="text/javascript">
        var loadButton = document.getElementById('load-more');
        var feed = new Instafeed({
            clientId: '<client ID>',
            get: 'user',
            userId: '<user ID>',
            accessToken: '<access token>',
            template: '<a href="{{link}}" class="grid-gallery-item" target="_blank"><img src="{{image}}" /></a>',
            resolution: 'standard_resolution',
            limit: 60,
            after: function() {
                if (!this.hasNext()) {
                    loadButton.setAttribute('disabled', 'disabled');
                }
            }
        });

        loadButton.addEventListener('click', function() {
            feed.next();
        });

        feed.run();
    </script>
</div>
```

**Comment by benjamin-hull** [comment]
This is a limitation of CSS Grid as used here, rather than a problem with instafeed.js itself. The grid layout is trying to fit your items into the grid as closely as possible, but depending on the order and size of those items, and the containing space, it might not be possible to do so without gaps. There's a good explanation here: https://medium.com/@js_tut/css-grid-tutorial-filling-in-the-gaps-c596c9534611#6e47 and a quick a demonstration: https://codepen.io/benjamin-hull/pen/KeEwOo 

As far as I understand, the basic problem is that the layout engine doesn't 'look back' as it lays out the cells - it will put the item currently being worked with in the _next_ suitable cell, but it won't look back and try to fill any _previous_ gap, even if the item would fit.

I'm fairly sure you can use start and end rules to define the grid differently so that this doesn't happen, but I haven't used it myself.

Another option is to use a javascript grid layout library like [Packery](https://packery.metafizzy.co/) - this does 'look back', and so can produce a gapless layout. I've used this on a lot of projects and it works really well.

**Comment by benjamin-hull** [comment]
I'm going to close this issue as it's outside of instafeed's scope, but feel free to let me know how you go with the layout. Good luck!
