### ISSUE TITLE
How to get ACCESS_TOKEN?

### ISSUE THREAD

**Issue by keslo** [stevenschobert/instafeed.js#603]
Hello!
How to get `access_token`?
Thanks!

**Comment by benjamin-hull** [comment]
Hi @keslo - the Instagram API docs have information on getting an access token: https://www.instagram.com/developer/authentication/

Be aware that due to Instagram's sandbox limitations, you'll need to be logged in as the user whose feed you want to access with instafeed.js. The instagram docs aren't really designed for this use, so many people use a tool such as [this one](http://instagram.pixelunion.net/). Please note that authorising any third party tool such as this is at your own risk!
