### ISSUE TITLE
Instafeed get:popular / get:tagged

### ISSUE THREAD

**Issue by davidhurwich** [stevenschobert/instafeed.js#606]
I'm a web development teacher who is using the instafeed.js to teach my students about APIs.

I have used instafeed to so students can embed their own instagram feeds, but I was hoping to have them be able to bring in other images through get:'popular' and 'get:tagged'. I've tried both and can't seem to get images to be brought in. 

Is this feature still working? I've looked online for working examples, but I only find examples of get:user. I have my clientId and I am not getting results. Any info would be appreciated.

**Comment by benjamin-hull** [comment]
Hi @davidhurwich, sorry to be the bearer of bad news, but these features are no longer supported by the Instagram API. Instagram are in the process of deprecating this API in favour of one based on Facebook's OpenGraph, however it looks like this will be at least targeted to, if not limited to, business profiles. There's more information here and in Instafeed's readme: https://github.com/stevenschobert/instafeed.js/issues/345

If you're looking to teach students about REST APIs, then the [Flickr API](https://www.flickr.com/services/developer/api/) might be a good choice - unlike Instagram they encourage tinkering, and they always prided themselves on good URL structure (it's been a while since I used it).

Not sure about a client-side equivalent to instafeed.js, but I'm sure there's something out there.

I'm going to close this issue, but do post back if you need more help. Hope that's useful - good luck!
