### ISSUE TITLE
Multiple Feeds Loop with Success Function

### ISSUE THREAD

**Issue by SteGreig** [stevenschobert/instafeed.js#608]
Hi there, I'm using a for loop in order to run multiple feeds as follows:

```javascript
var galImages = document.querySelectorAll('#instafeed li').length;
for(var i=0; i < galImages; i++) {
    var feed = new Instafeed({
	get: 'user',
	userId: '5489104071',
	accessToken: '5489104071.d4ba55e.7f902a2487c247bf9764651b70599536',
	template: '&lt;img width="366" height="366" src="{{image}}" /&gt;',
	limit: (i*2)+2,
	resolution: 'standard_resolution',
	target: 'insta-gal-'+(i+1),
	success: function(data){
                console.log(i); // returns 9 9 9 9 9 9 9 9 9
		images = data.data;
                var spliceNum = i*2;
		images.splice(0,spliceNum);
	}
    });
    feed.run();
}
```

My issue is, I need to use the `i` variable in the success function, but I'm not sure how I can do this. If I console.log `i` within the success function, instead of returning 1,2,3,4,5,6,7,8,9 it just returns 9,9,9,9,9,9,9,9,9.

Can anyone help?

**Comment by benjamin-hull** [comment]
Hey @SteGreig,

This is happening because the success callback is run asynchronously to your `for` loop - it runs when the remote call to instagram completes, by which time the `for` loop has continued, incremented the value of `i` and completed.

What you need is a way to provide the value of `i` _at the time the success callback was created_ to the body of the function. There are different ways to do that, but one simple one would be to store that value on the target element itself, and then retrieve it when the callback runs, something like this:

```` javascript
var galImages = document.querySelectorAll('#instafeed li').length;
for(var i=0; i < galImages; i++) {
  var target = document.querySelector('#insta-gal-'+(i+1));

  // Store the value of i on a data attribute on the target
  target.setAttribute('data-instafeed-set', i);
  
  var feed = new Instafeed({
    	get: 'user',
    	userId: '5489104071',
    	accessToken: '5489104071.d4ba55e.7f902a2487c247bf9764651b70599536',
    	template: '<img width="366" height="366" src="{{image}}">',
    	limit: (i*2)+2,
    	resolution: 'standard_resolution',
    	target: target, //Set the target to the DOM node directly
    	success: function(data){
        var i = parseInt(this.options.target.getAttribute('data-instafeed-set'));
        console.log(i); //Yields 0, 1, 2 ...
    		images = data.data;
        var spliceNum = i*2;
    		images.splice(0,spliceNum);
    	}
    });

  feed.run();
}
````

I haven't actually tested that (and I suspect there might be more efficient ways to approach what you're doing) but it should do the trick.

**Comment by exspeed** [comment]
Hi @benjamin-hull

I got this to work with _success_ callback, but this didn't seem to work with the _filter_ callback.

```
filter: function (image) {
            var i = parseInt(this.options.target.getAttribute('data-instafeed-set'));
            console.log(i); 
            return image.tags.indexOf(global_tag[i]) >= 0;
        }
```

I got the following error instead:
```
Uncaught TypeError: Cannot read property 'target' of undefined
```
