### ISSUE TITLE
Instafeed only showing 4 images

### ISSUE THREAD

**Issue by danieljpc** [stevenschobert/instafeed.js#615]
The instafeed at the foot of my page: https://thinkjpc.com/what-we-do/customer-experience/ is now only showing 4 images, it used to show 9 but has dwindled down to 4 and I don't know why.

```javascript
<script>
    var feed = new Instafeed({
        clientId: '________',
        accessToken: '________',
		get: 'tagged',
        tagName: 'jpcwip',
        clientId: '________',
        template: '<a href="{{link}}"><img src="{{image}}" /></a>',
        target: 'instagramfeed',
		limit: 9,
        resolution: 'standard_resolution',
        template: '<a class="instagram-image" href="{{link}}" target="_blank"><img src="{{image}}"/></a>',
		after: function() {
			var el = document.getElementById('instagramfeed');
			if (el.classList)
				el.classList.add('show');
			else
				el.className += ' ' + 'show';
		}
});
window.onload = function() {
	feed.run();
};
	</script>
```

**Comment by Nicolas-Cargo** [comment]
Same for me. Used to work with 6 and now only show 5.. Don't know why.
I've passed limit from 6 to 7 and it now show the first 6.. But it's quite unintuitive..

**Comment by benjamin-hull** [comment]
Hi @danieljpc and @Nicolas-Cargo - the answer here is that instafeed does its tag-filtering _after_ the `limit` number of images have been fetched, because instagram's API no longer allows direct retrieval by tag. What happens is "Give me 9 images, then show the ones with tag #jpcwip", not "Give me 9 images tagged with #jpcwip".

Because sandbox mode limits you to 20 images, when filtering by tag you're generally best to just fetch all 20. That's no guarantee that you'll get the number of tagged images you expect, but it's the best the API can give us.

**Comment by benjamin-hull** [comment]
If you're just using `get: 'user', userId: 'USER_ID', limit: 8`, I would expect you'd get the 8 most recent images for that user. If that's not what is happening, is there a URL you can share which shows the problem?

**Comment by Nicolas-Cargo** [comment]
You can re-close the issue, it's working now. When I posted the issue, in november, in order to fetch 6 images, I needed to set limit to 7.. Few days after, the website was showing me 7 images ! So I change it to 6 and it's working since.
It's for this homepage, bottom area : https://bit.ly/2H3TsKF

**Comment by benjamin-hull** [comment]
That's interesting (and strange!). Glad it's working now!
