### ISSUE TITLE
Firefox blocking the script

### ISSUE THREAD

**Issue by alFrame** [stevenschobert/instafeed.js#633]
FireFox 67.0.2 on Windows seems to block the script. I get "Loading failed for the <script> with source..." Works fine in Chrome, Edge, IE 11, Opera and Brave.

Only if I run FireFox in save mode it works. Tried disabling all other scripts and also disabled AddBlocker.

I see an old issue #625 about the same problem that was closed by the author.

Sorry, forgot to add the URL: https://staernefee.ch/

**Comment by alFrame** [comment]
Hey there, anyone still actively using or developing on this? Or is it a matter of waiting until FireFox cleans up it's act?

**Comment by benjamin-hull** [comment]
Hi @alFrame, apologies for the delay in replying. Development and support on instafeed.js has slowed, largely due to the coming API changes at Instagram. 

Regarding your site, I can see the the Instagram feed in Firefox 67.0.4 under MacOS no problem. The fact that it works in a private session strongly suggests that it's caused by an add-on or other user script. I've seen privacy add-ons block instafeed.js before because they look for things with 'insta' in their name.

Have you tried visiting [about:addons](about:addons) and temporarily disabling your add-ons? If that fixes it, try re-enabling them one at a time until you find the culprit.

**Comment by alFrame** [comment]
Hi @benjamin-hull Thanks for the info. Indeed the Facebook-Container AddOn was causing the issue.

Thanks!
