### ISSUE TITLE
Uncaught Error: Error from Instagram: The access_token provided is invalid.

### ISSUE THREAD

**Issue by feeohnah** [stevenschobert/instafeed.js#693]
I upgraded to Instafeed v2 and followed the instructions to set up the token agent which is here: [https://fondfolio-instagram.herokuapp.com/](https://fondfolio-instagram.herokuapp.com/) and seems to be working, but I'm getting an invalid token error on my website [https://fondfolio.com/](https://fondfolio.com/) and can't figure out why. 

[Here’s where I’m loading the Token Agent script](https://github.com/studio-cartogram/fondfolio-home/blob/master/app/themes/fondfolio/partials/head.php)

[Here’s where I’m calling it in the js](https://github.com/studio-cartogram/fondfolio-home/blob/d86db563eb6c813852e22ea7bae065a81afd1fb1/app/themes/fondfolio-dev/assets/js/main.js#L78)

What am I missing?

**Comment by benjamin-hull** [comment]
Hi @feeohnah - looking at your token agent, I can see it's loading correctly, so that bit looks fine, at least. 

Looking at fondfolio.com, I can't see that the token agent is being loaded - had you removed it because it's not working? The error I can see is `Uncaught ReferenceError: InstagramToken is not defined`, rather than an invalid token error.

**Comment by feeohnah** [comment]
That’s strange. No I didn't remove it. I wonder why we're seeing different errors?

<img width="1277" alt="Screen Shot 2020-08-20 at 10 12 27 AM" src="https://user-images.githubusercontent.com/2460068/90783192-c8027a00-e2cd-11ea-88ab-5bf75098ce67.png">

**Comment by t4ce** [comment]
I might have a hint for you here. As you are upgrading from version 1, this error might aswell be caused by the old sources still in place. So recompile and double check, that you have the new instafeed.js and just hardcopy the LONGLIVE token (60 days) like this, to give it a quick try:
`    <div id="instafeed"></div>

    <script type="text/javascript">
        var feed = new Instafeed({
            accessToken: 'IGQVJVX0syUH....YOUR_TOKEN'
            , debug: true
        });
        feed.run();
    </script>`

**Comment by techguydev** [comment]
I was having the same error, it was because I was using version 1.4 from a CDN.

Try to load the latest version of this library from the dist folder and install it in your project and it will work, I've just tested it.
